kumuluzee:
  name: analyzed-trip-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/AnalyzedTripDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5435/analyzed-trip-data
      username: dbuser
      password: postgres
      pool:
        max-size: 5
  config:
    consul:
      agent: http://52.224.38.169:80
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/AnalyzedTripDataDS
  metrics:
    web-instrumentation:
      - name: analyzed-trip-endpoint
        url-pattern: /v1/analyzed-trips
rest-properties:
  config:
    broken: false
